apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: ./base/kustomization.yaml  # Ensure the correct relative path is set
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: test-namespace
  timeout: 5m
  wait: true
